<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://impl.arthematic.jaxws.javaee7.org/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://arthematic.jaxws.javaee7.org/" name="arithmeticCalculator" targetNamespace="http://impl.arthematic.jaxws.javaee7.org/">
  <wsdl:import location="http://185.170.48.161:80/sample-jaxrs-btm-top/arithmeticCalculator?wsdl=ArithmeticCalculator.wsdl" namespace="http://arthematic.jaxws.javaee7.org/">
    </wsdl:import>
  <wsdl:binding name="arithmeticCalculatorSoapBinding" type="ns1:ArithmeticCalculator">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="calculateExpression">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="calculateExpression">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="calculateExpressionResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="ArithmeticCalculationException">
        <soap:fault name="ArithmeticCalculationException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="arithmeticCalculator">
    <wsdl:port binding="tns:arithmeticCalculatorSoapBinding" name="ArithmeticCalculatorImplPort">
      <soap:address location="http://185.170.48.161:80/sample-jaxrs-btm-top/arithmeticCalculator"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>